index:
    path: /
    controller: App\Controller\HomeController::index

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

register:
    methods: GET
    path: /register
    controller: App\Controller\SecurityController::register

register.store:
    methods: POST
    path: /register
    controller: App\Controller\SecurityController::store

account:
    path: /account
    controller: App\Controller\HomeController::account

admin:
    path: /admin
    controller: App\Controller\Admin\AdminController::index

admin.users:
    path: /admin/users
    controller: App\Controller\Admin\UsersController::index

admin.users.normal:
    path: /admin/users/normal
    controller: App\Controller\Admin\UsersController::normal

admin.users.admin:
    path: /admin/users/admin
    controller: App\Controller\Admin\UsersController::admin
