index:
    path: /
    controller: App\Controller\HomeController::index

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

register:
    methods: GET
    path: /register
    controller: App\Controller\SecurityController::register

register.store:
    methods: POST
    path: /register
    controller: App\Controller\SecurityController::store

account:
    methods: GET
    path: /account
    controller: App\Controller\User\AccountController::index

account.store:
    methods: POST
    path: /account
    controller: App\Controller\User\AccountController::store

account.address:
    methods: GET
    path: /account/address
    controller: App\Controller\User\AddressController::index

account.address.create:
    methods: GET
    path: /account/address/new
    controller: App\Controller\User\AddressController::create

account.address.store:
    methods: POST
    path: /account/address/new
    controller: App\Controller\User\AddressController::store

account.address.edit:
    methods: GET
    path: /account/address/{address}
    controller: App\Controller\User\AddressController::edit

account.address.update:
    methods: PATCH
    path: /account/address/{address}
    controller: App\Controller\User\AddressController::update

account.address.destroy:
    methods: DELETE
    path: /account/address/{address}
    controller: App\Controller\User\AddressController::destroy

admin:
    path: /admin
    controller: App\Controller\Admin\AdminController::index

admin.users:
    path: /admin/users
    controller: App\Controller\Admin\UsersController::index

admin.users.normal:
    path: /admin/users/normal
    controller: App\Controller\Admin\UsersController::normal

admin.users.admin:
    path: /admin/users/admin
    controller: App\Controller\Admin\UsersController::admin
