index:
    path: /
    controller: App\Controller\HomeController::index

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

register:
    methods: GET
    path: /register
    controller: App\Controller\SecurityController::register

register.store:
    methods: POST
    path: /register
    controller: App\Controller\SecurityController::store

account:
    path: /account
    controller: App\Controller\HomeController::account

dashboard:
    path: /admin
    controller: App\Controller\Admin\AdminController::index
